### PR TITLE
  Allow update taxonomy to use unzipped dmp files

### PR DESCRIPTION
**Pull request by yesimon**
Only when `--local` is true.

Also allow relative paths for $taxonomyPath.

### CODE REVIEW

**Comment by ondovb** [comment]
I get a syntax error at line 123 on OSX when running without local.

**Comment by yesimon** [comment]
I've updated it to handle without local.

**Comment by ondovb** [comment]
The test at 123 still doesn't work for me when $local is blank, and also doesn't seem like it would check the timestamp. Also the popd seems to prevent generation of taxonomy.tab. There will be a new release soon to address GIs going away; I'll try to look into these improvements at the same time.

**Comment by yesimon** [comment]
Ok, the issues I'm trying to address are:

I want `--local` to support building database directly from unzipped `*.dmp` files. I'm using a directory of unzipped `dmp` files for other purposes and I don't want to zip them up just to unzip them right after. In this case, checking timestamp doesn't mean anything because I manually placed the unzipped `*.dmp` files there myself, and either there won't be a `.dat` file or it will be up to date. Therefore `.dat` and `.tab` files are unneeded if `--local` is building from unzipped `*.dmp` files.

Secondly, by `cd $taxonomyPath`, it forces the `$taxonomyPath` argument to be an absolute path, because later references to `$taxonomyPath` after `cd $taxonomyPath` will double the relative path. The purpose of `pushd/popd` is to temporarily chdir to `$taxonomyPath` 

Thanks for your hard work!

**Comment by ondovb** [comment]
The overhauled updateTaxonomy.sh (with accessions and makefiles) now on master should address all of these issues if you'd like to try it out before the official release. There is also a --preserve option if you want to keep the files around for other uses. Note that instead of the gi_taxid dumps, it expects the accession2taxid files from ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/ (taxdump.tar is still the same).

**Pull request closed without merging**
